branches:
  only:
    - master
language: node_js
node_js:
  - iojs-v1.2.0
addons:
  ssh_known_hosts: parisleaf.com
sudo: false

# Begin Build Lifecycle
#
# 1. before_install
before_install:
  - openssl aes-256-cbc -K $encrypted_5dd9bc9d7f79_key -iv $encrypted_5dd9bc9d7f79_iv -in .travis/deploy_key.pem.enc -out .travis/deploy_key.pem -d
# 2. install
# 3. before_script
before_script:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\tPasswordAuthentication no\n" >> ~/.ssh/config
# 4. script
# 5. after_success or after_failure
after_success:
  # see https://docs.travis-ci.com/user/deployment/custom/
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - git remote add deploy dokku@paisleaf.com:production
  - git push deploy
# 6. OPTIONAL before_deploy
# 7. OPTIONAL deploy
# 8. OPTIONAL after_deploy
# 9. after_script
